Docs: update readme
filecoin-project/bacalhau pull request #1598
Opened 2023-01-05 12:54 UTC by fakela

2023-01-05 16:28 UTC, it09 requested changes
It's a good start!
Some suggestions:
* keep benefits 
* move Current state of B to https://www.notion.so/pl-strflt/Compute-Over-Data-25fa366465ed4ddf81027498efb4a405
* move get the latest B updates to https://www.notion.so/pl-strflt/Compute-Over-Data-25fa366465ed4ddf81027498efb4a405
* checkout this blog on how to write README and what should be in it: https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md

This is a list of README examples for reference
 - https://github.com/filecoin-project/mir
 - https://github.com/filecoin-project/neptune
 - https://github.com/filecoin-project/ref-fvm
 - https://github.com/filecoin-project/fvm-specs
 - https://github.com/filecoin-project/wasmtime - for a new project, you can add features/advantages section

2023-01-05 19:53 UTC, fakela commented
> It's a good start! Some suggestions:
> 
> * keep benefits
> * move Current state of B to https://www.notion.so/pl-strflt/Compute-Over-Data-25fa366465ed4ddf81027498efb4a405
> * move get the latest B updates to https://www.notion.so/pl-strflt/Compute-Over-Data-25fa366465ed4ddf81027498efb4a405
> * checkout this blog on how to write README and what should be in it: https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md
> 
> This is a list of README examples for reference
> 
> * https://github.com/filecoin-project/mir
> * https://github.com/filecoin-project/neptune
> * https://github.com/filecoin-project/ref-fvm
> * https://github.com/filecoin-project/fvm-specs
> * https://github.com/filecoin-project/wasmtime - for a new project, you can add features/advantages section

Thanks for the comment and suggestions @it09, just to be clear the current state of B and latest B updates, I should add the link to the notion instead than listing everything out.

2023-01-09 20:41 UTC, fakela commented
@it09 I have made updates following the suggestions

2023-01-12 07:30 UTC, simonwo reviewed
Looks great!

2023-01-12 07:30 UTC, simonwo commented on README.md
> +- **Large-scale data**: With Bacalhau, you can manage your own containers that can scale to batch process petabytes (quadrillion bytes) files.
> you can manage your own containers

What management are we referring to? I’d rather be running processing without managing stuff!

2023-01-12 10:23 UTC, fakela commented
@simonwo i have rephrased the sentences to be clear and just highlight what we offer

2023-01-17 10:51 UTC, closed without merging