Bacalhau command jobspec jsonyaml generate dryrun
filecoin-project/bacalhau pull request #536
Opened 2022-08-29 05:18 UTC by js-ts

Commands

Convert the command into a yaml jobspec and submit to the network
`bacalhau --output-jobspec job-hello.yml ubuntu echo hello`

Convert the command into a yaml jobspec, without submitting to the network
`bacalhau --output-jobspec job-hello.yml --dry-run ubuntu echo hello`

Convert the command into a json jobspec and submit to the network
`bacalhau --output-jobspec job-hello.json ubuntu echo hello`

Convert the command into a json jobspec, without submitting to the network
`bacalhau --output-jobspec job-hello.json --dry-run ubuntu echo hello`

2022-08-29 22:31 UTC, aronchick requested changes
Thanks for working on this - please make these changes.

Also, your test case should be using `bacalhau create -f` the file you outputted - and see if the job is created.

2022-08-29 22:31 UTC, aronchick commented on cmd/bacalhau/docker_run.go
> +		`Run a Job withtout Submitting it to the network`,
This isn't correct - you're not running a job - you're simulating running a job, right? And outputting what is expected?

2022-08-29 22:31 UTC, aronchick commented on cmd/bacalhau/docker_run.go
> +	dockerRunCmd.PersistentFlags().StringVar(
Please remove. This is not required. You should just print the jobspec to stdout.

2022-08-29 22:31 UTC, aronchick commented on cmd/bacalhau/docker_run.go
> +		if !ODR.DryRun {
Don't do this. Just see if it's a DryRun, and if it is, print out the jobspec, and return.

2022-08-29 22:31 UTC, aronchick commented on cmd/bacalhau/docker_run.go
> +		if ODR.OutputFileName != "" {
Delete all this

2022-08-29 22:31 UTC, aronchick commented on cmd/bacalhau/utils.go
> +func ConvertJobspecToFile(
Delete all this. Please reuse the functionality in Describe to unmarshall the object into a YAML/JSON file. We don't need to support both - just use YAML.

2022-08-30 09:23 UTC, binocarlos commented on cmd/bacalhau/docker_run.go
>  		}
We need to move this error block inside the `!ODR.DryRun` otherwise this is refering to the error before and so is having no affect

2022-08-30 09:24 UTC, binocarlos commented on cmd/bacalhau/docker_run.go
> +		}
We need to move this error catching code inside the !ODR.DryRun block otherwise this is refering to the error before and so is having no affect

2022-08-30 09:26 UTC, binocarlos reviewed
I think it might be nice to also run `VerifyJob` as part of doing a dry run

We run `VerifyJob` from inside the api server and because this request is never getting sent to the server we miss out on all of it's goodness (there will be occasions when `VerifyJob` will catch silly errors and so makes sense to run that on the client)

^ there is probably the case from running verify job ALWAYS in the CLI - as in we should run it even if dry run is not activated

Here is an example:

```go
err := job.VerifyJob(jobSpec, jobDeal)
if err != nil {
  return fmt.Errorf("error validating job: %s", err)
}
```

2022-09-09 06:34 UTC, closed without merging