bacalhau validate
filecoin-project/bacalhau pull request #657
Opened 2022-09-23 10:11 UTC by js-ts

`bacalhau validate ./testdata/job.yaml `
The JobSpec is valid

`bacalhau validate ./testdata/job-invalid.yml `
The JobSpec is not valid. see errors :
- (root): apiVersion is required

2022-09-23 12:15 UTC, aronchick requested changes

2022-09-23 12:15 UTC, aronchick commented on cmd/bacalhau/validate.go
> +		if fileextension == ".json" {
I’ve seen this pattern a couple of times in the code and it’s always bugged me (lots of things don’t have file extensions, like stdin). I wonder if a solution like this - https://stackoverflow.com/a/68159730/4322 - is more elegant. Regardless, we should use generics, and move to a function

2022-09-23 14:58 UTC, js-ts commented on cmd/bacalhau/validate.go
> +		s := jsonschema.Reflect(&model.JobSpec{})
No checks neccesarry the schema is auto generated from the struct
if you enter int instead of string it will throw an error

2022-09-25 15:48 UTC, aronchick approved these changes

2022-09-25 15:48 UTC, merged